### PR TITLE
RAD-4162 Sync file download for unit test validation

### PR DESCRIPTION
**Pull request by MertCingoz**
## Description

Fix for [flaky tests](https://ci.radixiot.team/buildConfiguration/Mango_Mango5_CompleteBuild/42878?buildTab=tests&status=failed&expandedTest=build%3A%28id%3A42878%29%2Cid%3A25761) that requires validating downloaded file content

### CODE REVIEW

**Comment by jazdw** [comment]
Looks correct to me @MertCingoz 
Any reason its not ready for review?

**Comment by MertCingoz** [comment]
It is ready, we were about to move npm organization from https://www.npmjs.com/org/infinite-automation  to https://www.npmjs.com/org/radixiot. Since you are the only one can access and release npm packages right now.

**Comment by jazdw** [comment]
> Since you are the only one can access and release npm packages right now. 

@terrypacker has access too. But yes we should move it to a new org.

**Review by jazdw — APPROVED** [review]

**Comment by terrypacker** [comment]
@jazdw I couldn't get it as it uses my old IAS email address.  I will make a note to see if I can fix that or maybe just open new account for Radix?

**Comment by jazdw** [comment]
I invited your Radix email address to the infinite-automation org.

**Comment by jazdw** [comment]
FYI the radixiot org already exists, but I am not an owner.
https://www.npmjs.com/package/@radixiot/react-cache-buster

**Pull request merged**
